[package]
name = "kybr"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
argmin = "0.10.0"
argmin-observer-slog = "0.1.0"
iced = "0.13.1"
include_data = "1.0.1"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
